/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include <unity/unity.h>
#include <setjmp.h>
#include <stdio.h>
#include "bheap.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_bheap_empty_peek_and_extract(void);
extern void test_bheap_peek_extract_peek(void);
extern void test_bheap_min_heap(void);
extern void test_bheap_max_heap(void);
extern void test_bheap_heapify(void);
extern void test_bheap_inverse_heapify(void);
extern void test_bheap_sort(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("../test/bheap_test.c");
  RUN_TEST(test_bheap_empty_peek_and_extract, 37);
  RUN_TEST(test_bheap_peek_extract_peek, 51);
  RUN_TEST(test_bheap_min_heap, 88);
  RUN_TEST(test_bheap_max_heap, 109);
  RUN_TEST(test_bheap_heapify, 187);
  RUN_TEST(test_bheap_inverse_heapify, 217);
  RUN_TEST(test_bheap_sort, 246);

  return (UnityEnd());
}
