/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include <unity/unity.h>
#include <setjmp.h>
#include <stdio.h>
#include "queue.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_queue_pop_empty(void);
extern void test_queue_push_peek(void);
extern void test_queue_push_peek_pop(void);
extern void test_queue_fifo_load_then_traverse(void);
extern void test_queue_fifo_load_with_traverse(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("../test/queue_test.c");
  RUN_TEST(test_queue_pop_empty, 16);
  RUN_TEST(test_queue_push_peek, 21);
  RUN_TEST(test_queue_push_peek_pop, 27);
  RUN_TEST(test_queue_fifo_load_then_traverse, 37);
  RUN_TEST(test_queue_fifo_load_with_traverse, 49);

  return (UnityEnd());
}
